---
version: 2
jobs:
  build:
    working_directory: /root/meta_pid

    docker:
      - image: avvo/elixir-circleci:1.4.1-3

    environment:
      MIX_ENV: test

    steps:
      - checkout

      - restore_cache:
          key: meta_pid-{{ .Branch }}
          key: meta_pid-master

      - run: mix do deps.get, deps.compile, compile

      - save_cache:
          key: meta_pid-{{ .Branch }}
          key: meta_pid-master
          paths:
            - _build
            - deps

      - run:
          name: Run Tests
          command: mix test
